Week1_Exercise
pesto-students/p3-shashank-HarshitPatel95 pull request #2
Opened 2022-06-18 13:25 UTC by HarshitPatel95

Please review and let me know what you think.

2022-06-22 14:44 UTC, ShashankSuresh requested changes

2022-06-22 14:44 UTC, ShashankSuresh commented on Week-1/Exercise1.2/index.html
> +    <main>
can we have a parent class?

2022-06-22 14:44 UTC, ShashankSuresh commented on Week-1/Exercise1.2/css/style.css
> +  font-family: Lato, sans-serif;
Lets have common classes to all HTML elements using the `*` css selector 

```
* {
font-family: Lato, sans-serif;
}
```

2022-06-22 14:44 UTC, ShashankSuresh commented on Week-1/Exercise1.2/css/style.css
> +  background-color: #e3dfdf;
Lets have these in css variables

2022-06-22 14:44 UTC, ShashankSuresh commented on Week-1/Exercise1.2/css/style.css
> +html {
Lets have parents included to all children and grand-children

2022-06-22 14:44 UTC, ShashankSuresh commented on Week-1/Exercise1.1/readme.md
> +# Exercise1.1
Looks good. 

Can we have information about DNS - how it works, its purpose, caching, CDN etc ?
Can we also talk a bit more about what the response from the server looks like and how that is converted to DOM (HTML DOM + CSS DOM)

2022-06-22 15:03 UTC, ShashankSuresh commented on Week-1/Exercise1.2/css/style.css
> +  --white: #ffffff;
Good job :)

2022-06-24 03:58 UTC, HarshitPatel95 commented on Week-1/Exercise1.2/index.html
> +    <main>
I have already done this change in my last commit with message name "feedback changes"

2022-06-24 03:58 UTC, HarshitPatel95 commented on Week-1/Exercise1.2/css/style.css
> +html {
I have already done this change in my last commit with message name "feedback changes"

2022-06-24 10:42 UTC, ShashankSuresh requested changes

2022-06-24 10:42 UTC, ShashankSuresh commented on Week-1/Exercise1.2/css/style.css
>    background-color: #5981bd;
Please add this to css variables.

2022-06-24 10:42 UTC, ShashankSuresh commented on Week-1/Exercise1.2/css/style.css
>    background-color: #ededed;
Please add this to css variables.

2022-06-24 12:48 UTC, ShashankSuresh approved these changes
Good job :)

2022-06-24 13:23 UTC, merged